### PR TITLE
Committing Try2 BranchX

### PR DESCRIPTION
**Pull request by ayumanshor**
Hi 
I have committed Try 2

### CODE REVIEW

**Comment by noridayu2021** [comment]
Hi X
Your code look good

**Comment by ayumanshor** [comment]
Add terkini please check

**Comment by noridayu2021** [comment]
ok really good

**Comment by ayumanshor** [comment]
I have add 19 okt message

**Comment by ayumanshor** [comment]
I have added new class

**Comment by noridayu2021** [comment]
noted

**Pull request merged**
